project_id = "itryqwkqnexuawvpoetz"

[functions.transcribe-lyrics]
verify_jwt = false

[functions.chat-with-yuki]
verify_jwt = false

[functions.blog-ai]
verify_jwt = false

[functions.blog-tts]
verify_jwt = false

[functions.check-scheduled-posts]
verify_jwt = false

[functions.generate-ogp]
verify_jwt = false
